### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by nunojesus** [chrisguttandin/midi-player#182]
Hello can you give me more informations about this project? Im a graphic designer that contributes for opensource projects like yours, so if you need some help to create a logotype or other stuff just say it.

Greetings

**Comment by chrisguttandin** [comment]
Hello @nunojesus, thanks for your kind offer. You're right, I should finally add some text to the README of this project. I will try to find some time to do it as soon as possible.

**Comment by nunojesus** [comment]
Hi @chrisguttandin do you need a logo for this project?

**Comment by chrisguttandin** [comment]
I think it is better to first add some documentation before adding a logo. Adding a logo now feels a bit like making the second step before the first.
