### ISSUE TITLE
Synchronizing UI elements

### ISSUE THREAD

**Issue by infojunkie** [chrisguttandin/midi-player#345]
I'm a big fan of your audio libraries, and I'm considering using your MIDI player for an app I'm working on. I do have a question: what do you recommend to keep the UI synchronized with the scheduled MIDI events that are emitted here? I imagine I could write a "proxy" `MIDIOutput` object that schedules UI updates or callback events, but I am wondering if you already have some code that does this, which would be of great help.

Thanks!

**Comment by chrisguttandin** [comment]
Hi Karim,

thanks for your kind words. I think I don't have a readymade answer to your question. Are you planning to highlight the currently played notes in the UI?

**Comment by infojunkie** [comment]
Yes, this and updating the chrome of the MIDI player.

**Comment by chrisguttandin** [comment]
I'm not sure if it makes sense to reuse the midi-player to update the UI. It uses `setInterval()` internally to schedule the MIDI message with a look ahead. Maybe it's better to use `requestAnimationFrame()` for UI updates.

But the code which is internally used to slice the MIDI file into parts is published as a standalone module. It's called [midi-file-slicer](https://github.com/chrisguttandin/midi-file-slicer).

I haven't tested it, but something like this should work:

```js
import { MidiFileSlicer } from 'midi-file-slicer';

const midiFileSlicer = new MidiFileSlicer({ json /* json obtained with midi-json-parser */ });
const offset = performance.now();

let lastTime = offset;

const displayEvents = (now) => {
  const events = midiFileSlicer.slice(lastTime - offset, now - offset);
 
  // display events

  lastTime = now;

  requestAnimationFrame(displayEvents);
};

requestAnimationFrame(displayEvents);
```

**Comment by infojunkie** [comment]
Sounds promising, thanks! I'll follow this route and report back here. In the meantime, I think it's safe to close this (non-)issue.

**Comment by chrisguttandin** [comment]
I hope it works as expected. Please feel free to open a new issue here or on the midi-file-slicer repo if you run into any problem.
