### ISSUE TITLE
Export Scheduler

### ISSUE THREAD

**Issue by infojunkie** [chrisguttandin/midi-player#347]
Since the player constructor accepts a `scheduler` argument, it would be great to export your own `Scheduler` class that clients can reuse and extend instead of duplicating code.

**Comment by infojunkie** [comment]
Yes, that's exactly it, thanks!

**Comment by chrisguttandin** [comment]
I'm not particularly happy with the `Scheduler` class right now. I initially wanted to make it RxJS-y (if that's a word :-)) but I think I failed.

My current thinking is that it should just be a function which takes a callback and returns another function to unsubscribe again.

But before I do that it would be interesting to know your use case. Why do you need to extend the current `Scheduler`? What do you want to change/extend/re-use?

**Comment by infojunkie** [comment]
I initially wanted to reuse the scheduler to update the score cursor movements based on the same clock as the player. But thanks to your helpful advice I was able to manage differently and it's working great. So at the moment, feel free to close this request.
