### ISSUE TITLE
Stop scheduled MIDI notes

### ISSUE THREAD

**Issue by chrisguttandin** [chrisguttandin/midi-player#359]
I think calling `clear()` on the `midiOutput` and sending an "all sound off" message would be a good task to continue the work started in #357.

**Comment by chrisguttandin** [comment]
Hi @infojunkie, I noticed that you send "all sound off" messages to channel 1 to 16 in your implementation. Shouldn't it be channel 0 to 15?

https://github.com/infojunkie/midi-player/blob/1ec41f6d3e8e2a638342128128ae9d54074ae93c/src/midi-player.ts#L120

I guess it doesn't matter in the end since the encoding wraps around 16 to 0 anyway. I was just curious if there is something I'm missing.

**Comment by infojunkie** [comment]
Thanks for reporting Chris! I will fix this in my fork.
