### ISSUE TITLE
Implement pause()/resume()

### ISSUE THREAD

**Issue by chrisguttandin** [chrisguttandin/midi-player#361]
Next up after implementing #359 is adding the ability to pause and resume the player with dedicated methods as they already exist in @infojunkie's fork.

https://github.com/infojunkie/midi-player/blob/d8d6877279db7488a8599daa3d6b345c6f49aea8/src/midi-player.ts#L57-L67

https://github.com/infojunkie/midi-player/blob/d8d6877279db7488a8599daa3d6b345c6f49aea8/src/midi-player.ts#L83-L93

**Comment by infojunkie** [comment]
I've been attempting to catch up to your latest changes at https://github.com/infojunkie/midi-player/tree/merge-7.3.0. The current state of the branch is that pause / resume are functional again on top of 7.3.0. I think some changes in 7.3.2 will break, such as the functional scheduler refactor.

**Comment by infojunkie** [comment]
Update here: The merge with latest 7.3.4 is now complete. Tests are passing, new functionality (pause/resume/seek) is working.
