### ISSUE TITLE
stop() called too soon

### ISSUE THREAD

**Issue by infojunkie** [chrisguttandin/midi-player#362]
In this block https://github.com/chrisguttandin/midi-player/blob/ae91c1ce5a1902dbfc6bc1495eb55ea33b3c1e72/src/midi-player.ts#L77-L79 `_stop()` is called as soon as "End of Track" message is found.

However, some notes may still be scheduled for the future. This means that "All Sound Off" will be sent too early.

My solution is to maintain an additional state `latest` that calculates the latest scheduled event and only stops then 
https://github.com/infojunkie/midi-player/blob/c351943c1da33bd818e30e67e37174bfd268f71c/src/midi-player.ts#L160-L167

Maybe there would be a way to only use the scheduled time of the "End of Track" message itself as the latest time, but I'm not sure this would be reliable.

**Comment by chrisguttandin** [comment]
I think this is a confusion caused by my poor naming. `_stop()` is not sending the "All Sound Off" message it's only happening when calling the public `stop()` function.

`_stop()` should maybe be renamed to `_stopScheduler()`. What do you think?

**Comment by infojunkie** [comment]
Sorry, my description was wrong. What happens is that the promise is resolved as soon as the last event is found and scheduled, but potentially before it is processed by the MIDI output.

A client that is waiting on the promise will mistakenly think all the events have been processed too soon in this scenario. I will work on an illustration of this case in the coming few days.

**Comment by chrisguttandin** [comment]
Ah, I see. You mean the promise returned by `play()` resolves as soon as all the MIDI messages haven been sent, right?

I think that has always been the case. It's even mentioned in the readme:

> // All MIDI messages have been sent when the promise returned by play() resolves.

I think even if we somehow wait until `performance.now()` is `>=` when compared with the last scheduled event the MIDI device might still be playing something at that point. If I remember correctly that was the reason why I didn't bother adding it back then. But I'm happy to add it now if it's important for your use case.

**Comment by infojunkie** [comment]
An update here: 

I've added looping support to my fork, and to do so, I needed to precisely respect the MIDI file duration. You can see a demo at https://blog.karimratib.me/demos/musicxml/ - select "Baião Groove" from the list and set repeat to > 1.

The core of the technique relies on 2 pieces:
- Compute the MIDI duration https://github.com/infojunkie/midi-player/blob/main/src/midi-player.ts#L310
- Only resolve the promise when the elapsed time equals the duration above https://github.com/infojunkie/midi-player/blob/main/src/midi-player.ts#L276-L279

There's additional logic in there to support smooth looping with dropping beats, but that's irrelevant to this dicussion.
