### ISSUE TITLE
Wrong resolve after resume()

### ISSUE THREAD

**Issue by infojunkie** [chrisguttandin/midi-player#364]
I found this bug in my code, and looking at your code, I think it's there too. Consider the following scenario:

- Call `play()` => `state` is null => `state.resolve` is set
- Call `pause()` => `state.resolve()` is called, `state` remains non-null
- Call `resume()` => new `resolve` is passed, `state` is not null => `state.resolve` does not change
- Tracks end => old `state.resolve()` is called, new promise never resolves

**Comment by chrisguttandin** [comment]
Hi @infojunkie, thanks for letting me know.

I haven't made a manual test yet to verify my assumption but I think the following line should prevent this by resetting the `state` before scheduling the resumed playback.

https://github.com/chrisguttandin/midi-player/blob/056752558e573445fb08ba2fc978322a42685d0c/src/midi-player.ts#L67

There is also a test which checks that the promise gets resolved.

https://github.com/chrisguttandin/midi-player/blob/056752558e573445fb08ba2fc978322a42685d0c/test/unit/midi-player.js#L342-L346

**Comment by infojunkie** [comment]
Thanks for checking. Just thought I'd alert you, feel free to close this once you verify all's well.

**Comment by chrisguttandin** [comment]
Thank you @infojunkie, as always. I really appreciate it. I finally did a manual test to confirm that everything is working as expected, too. Luckily, it doesn't seem to be an issue.
